#!/usr/bin/env bash

usage() {
  echo "Usage: $0 {install|test|URL_FILE}"
  echo "  install   Install required Python packages"
  echo "  test      Run unit tests"
  echo "  URL_FILE  Absolute or relative path to a file with newline-delimited URLs"
}

# if no arguments or more than one argument is provided, show usage and exit
if [ "$#" -ne 1 ]; then
  usage
  exit 1
fi

# exit $? in each case so the python exit code is propagated
case "$1" in
  install)
    pip install -r requirements.txt
    exit $?
    ;;
  test)
    python3 -u run.py
    exit $?
    ;;
  *)
    python3 -u src/app.py "$1"
    exit $? 
    ;;
esac